#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if echo $BRANCH_NAME | grep '\-'; then
  ISSUE_ID=$(echo $BRANCH_NAME 2> /dev/null | grep -oE '[^-]\w*$')
  echo "$(cat $1) $ISSUE_ID" > $1
fi
